---
abstract: 'An efficient, tree-based, 2D multimatcher.'
author:
  - 'Daniel Șuteu <trizenx@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-MultiMatch
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: '0'
  perl: '5.01'
resources:
  repository: http://github.com/trizen/Search-MultiMatch
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
